#elasticsearch:
  #   comma separated
#  hosts: localhost:9200, localhost:9201

ELASTIC_HOSTS: ${ELASTIC_HOSTS}
ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  ### Only for testing individual microservices, remove during deployment.
  client:
    enabled: true
server.port: 8013

microservices:
  limesurvey-service:
    endpoints:
      activatePatientLSInfo: http://limesurvey-service/dashboard/activateLSInfo

spring:
  application:
    name: user-management
  #   eligibility answers
  data:
    elasticsearch:
      node:
        name: elasticsearch

  #   patients database
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/smartwork_usermgmt_dev
    #url: jdbc:mysql://mysql.idi.ntnu.no:3306/smartwork_usermgmt_dev
    url: ${MYSQL_URL}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    #        non spring-framework properties
    field-encryption:
      password: ${JPA_PASSWORD}
      salt: ${JPA_SALT}
